# Generated by Django 4.0.1 on 2022-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topnotch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='course/img/%y/%m/%d')),
                ('vids', models.FileField(upload_to='course/vids/%y/%m/%d')),
                ('audio', models.FileField(upload_to='course/audio/%y/%m/%d')),
            ],
        ),
    ]
